services:
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-schoolhub}'
            POSTGRES_USER: '${DB_USERNAME:-schoolhub}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
        networks:
            - schoolhub
networks:
    schoolhub:
        driver: bridge
volumes:
    pgsql:
        driver: local
