spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolhub
    username: postgres
    password: test12345
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.straightouttasteagu: debug
