export interface elementModel {
  inactive: boolean,
  symbol: string,
  name: string,
  mass: number,
  Z: number,
  valences: number[] | string,
  group: string,
  x: number,
  y: number
}

export interface compoundModel {
  
}

export interface parsedCompoundModel {
  parts: parsedElementModel[],
  type: 'acid' | 'base' | 'metal oxide' | 'nonmetal oxide' | 'salt' | 'metal' | 'nonmetal' | 'water' | 'hydrogen peroxide' | 'other' | null,
  baseElement: string,
  original: string
}

export interface parsedElementModel {
  element: string,
  amount: number,
  properties?: elementModel
}

export const tableElements: elementModel[] = [
  {inactive: false, symbol: 'H', name: 'Hydrogen', mass: 1.008, Z: 1, valences: [1], group: 'Other nonmetals', x: 1, y: 1},
  {inactive: true, symbol: 'He', name: 'Helium', mass: 4.0026, Z: 2, valences: 'doublet stable', group: 'Noble gases', x: 18, y: 1},
  {inactive: false, symbol: 'Li', name: 'Lithium', mass: 6.94, Z: 3, valences: [1], group: 'Alkali metals', x: 1, y: 2},
  {inactive: false, symbol: 'Be', name: 'Beryllium', mass: 9.0122, Z: 4, valences: [2], group: 'Alkaline earth metals', x: 2, y: 2},
  {inactive: false, symbol: 'B', name: 'Boron', mass: 10.81, Z: 5, valences: [3], group: 'Other nonmetals', x: 13, y: 2},
  {inactive: false, symbol: 'C', name: 'Carbon', mass: 12.011, Z: 6, valences: [2, 4], group: 'Other nonmetals', x: 14, y: 2},
  {inactive: false, symbol: 'N', name: 'Nitrogen', mass: 14.007, Z: 7, valences: [-3, -2, -1, 2, 3, 4, 5], group: 'Other nonmetals', x: 15, y: 2},
  {inactive: false, symbol: 'O', name: 'Oxygen', mass: 15.999, Z: 8, valences: [-2], group: 'Other nonmetals', x: 16, y: 2},
  {inactive: false, symbol: 'F', name: 'Fluorine', mass: 18.998, Z: 9, valences: [-1], group: 'Other nonmetals', x: 17, y: 2},
  {inactive: true, symbol: 'Ne', name: 'Neon', mass: 20.18, Z: 10, valences: 'doublet stable', group: 'Noble gases', x: 18, y: 2},
  {inactive: false, symbol: 'Na', name: 'Sodium', mass: 22.99, Z: 11, valences: [1], group: 'Alkali metals', x: 1, y: 3},
  {inactive: false, symbol: 'Mg', name: 'Magnesium', mass: 24.31, Z: 12, valences: [2], group: 'Alkaline earth metals', x: 2, y: 3},
  {inactive: false, symbol: 'Al', name: 'Aluminum', mass: 26.98, Z: 13, valences: [3], group: 'Other metals', x: 13, y: 3},
  {inactive: false, symbol: 'Si', name: 'Silicon', mass: 28.09, Z: 14, valences: [-4, 4], group: 'Other nonmetals', x: 14, y: 3},
  {inactive: false, symbol: 'P', name: 'Phosphorus', mass: 30.97, Z: 15, valences: [-3, 1, 3, 5], group: 'Other nonmetals', x: 15, y: 3},
  {inactive: false, symbol: 'S', name: 'Sulfur', mass: 32.07, Z: 16, valences: [-2, 2, 4, 6], group: 'Other nonmetals', x: 16, y: 3},
  {inactive: false, symbol: 'Cl', name: 'Chlorine', mass: 35.45, Z: 17, valences: [-1, 1, 3, 5, 7], group: 'Other nonmetals', x: 17, y: 3},
  {inactive: true, symbol: 'Ar', name: 'Argon', mass: 39.95, Z: 18, valences: 'doublet stable', group: 'Noble gases', x: 18, y: 3},
  {inactive: false, symbol: 'K', name: 'Potassium', mass: 39.10, Z: 19, valences: [1], group: 'Alkali metals', x: 1, y: 4},
  {inactive: false, symbol: 'Ca', name: 'Calcium', mass: 40.08, Z: 20, valences: [2], group: 'Alkaline earth metals', x: 2, y: 4},
  {inactive: true, symbol: 'Sc', name: 'Scandium', mass: 44.96, Z: 21, valences: [3], group: 'Transition metals', x: 3, y: 4},
  {inactive: true, symbol: 'Ti', name: 'Titanium', mass: 47.87, Z: 22, valences: [2, 3, 4], group: 'Transition metals', x: 4, y: 4},
  {inactive: true, symbol: 'V', name: 'Vanadium', mass: 50.94, Z: 23, valences: [2, 3, 4, 5], group: 'Transition metals', x: 5, y: 4},
  {inactive: false, symbol: 'Cr', name: 'Chromium', mass: 51.99, Z: 24, valences: [2, 3, 6], group: 'Transition metals', x: 6, y: 4},
  {inactive: false, symbol: 'Mn', name: 'Manganese', mass: 54.94, Z: 25, valences: [2, 3, 4, 5, 6, 7], group: 'Transition metals', x: 7, y: 4},
  {inactive: false, symbol: 'Fe', name: 'Iron', mass: 55.85, Z: 26, valences: [2, 3], group: 'Transition metals', x: 8, y: 4},
  {inactive: true, symbol: 'Co', name: 'Cobalt', mass: 58.93, Z: 27, valences: [2, 3, 4], group: 'Transition metals', x: 9, y: 4},
  {inactive: true, symbol: 'Ni', name: 'Nickel', mass: 58.69, Z: 28, valences: [2, 3, 4], group: 'Transition metals', x: 10, y: 4},
  {inactive: false, symbol: 'Cu', name: 'Copper', mass: 63.55, Z: 29, valences: [1, 2], group: 'Transition metals', x: 11, y: 4},
  {inactive: false, symbol: 'Zn', name: 'Zinc', mass: 65.38, Z: 30, valences: [2], group: 'Transition metals', x: 12, y: 4},
  {inactive: true, symbol: 'Ga', name: 'Gallium', mass: 69.72, Z: 31, valences: [1, 2, 3], group: 'Other metals', x: 13, y: 4},
  {inactive: true, symbol: 'Ge', name: 'Germanium', mass: 72.63, Z: 32, valences: [2, 4], group: 'Other nonmetals', x: 14, y: 4},
  {inactive: true, symbol: 'As', name: 'Arsenic', mass: 74.92, Z: 33, valences: [3, 5], group: 'Other nonmetals', x: 15, y: 4},
  {inactive: true, symbol: 'Se', name: 'Selenium', mass: 78.97, Z: 34, valences: [2, 4, 6], group: 'Other nonmetals', x: 16, y: 4},
  {inactive: false, symbol: 'Br', name: 'Bromine', mass: 79.90, Z: 35, valences: [-1, 1, 5], group: 'Other nonmetals', x: 17, y: 4},
  {inactive: true, symbol: 'Kr', name: 'Krypton', mass: 83.80, Z: 36, valences: 'doublet stable', group: 'Noble gases', x: 18, y: 4},
  {inactive: true, symbol: 'Rb', name: 'Rubidium', mass: 85.47, Z: 37, valences: [1], group: 'Alkali metals', x: 1, y: 5},
  {inactive: true, symbol: 'Sr', name: 'Strontium', mass: 87.62, Z: 38, valences: [2], group: 'Alkaline earth metals', x: 2, y: 5},
  {inactive: true, symbol: 'Y', name: 'Yttrium', mass: 88.91, Z: 39, valences: [3], group: 'Transition metals', x: 3, y: 5},
  {inactive: true, symbol: 'Zr', name: 'Zirconium', mass: 91.22, Z: 40, valences: [4], group: 'Transition metals', x: 4, y: 5},
  {inactive: true, symbol: 'Nb', name: 'Niobium', mass: 92.91, Z: 41, valences: [5], group: 'Transition metals', x: 5, y: 5},
  {inactive: true, symbol: 'Mo', name: 'Molybdenum', mass: 95.94, Z: 42, valences: [2, 3, 4, 5, 6], group: 'Transition metals', x: 6, y: 5},
  {inactive: true, symbol: 'Tc', name: 'Technetium', mass: 98.00, Z: 43, valences: [4, 7], group: 'Transition metals', x: 7, y: 5},
  {inactive: true, symbol: 'Ru', name: 'Ruthenium', mass: 101.1, Z: 44, valences: [2, 3, 4, 6, 8], group: 'Transition metals', x: 8, y: 5},
  {inactive: true, symbol: 'Rh', name: 'Rhodium', mass: 102.9, Z: 45, valences: [1, 2, 3, 4], group: 'Transition metals', x: 9, y: 5},
  {inactive: true, symbol: 'Pd', name: 'Palladium', mass: 106.4, Z: 46, valences: [2, 4], group: 'Transition metals', x: 10, y: 5},
  {inactive: true, symbol: 'Ag', name: 'Silver', mass: 107.9, Z: 47, valences: [1, 2, 3], group: 'Transition metals', x: 11, y: 5},
  {inactive: true, symbol: 'Cd', name: 'Cadmium', mass: 112.4, Z: 48, valences: [2], group: 'Transition metals', x: 12, y: 5},
  {inactive: true, symbol: 'In', name: 'Indium', mass: 114.8, Z: 49, valences: [1, 2, 3], group: 'Other metals', x: 13, y: 5},
  {inactive: true, symbol: 'Sn', name: 'Tin', mass: 118.7, Z: 50, valences: [2, 4], group: 'Other metals', x: 14, y: 5},
  {inactive: true, symbol: 'Sb', name: 'Antimony', mass: 121.8, Z: 51, valences: [3, 5], group: 'Other nonmetals', x: 15, y: 5},
  {inactive: true, symbol: 'Te', name: 'Tellurium', mass: 127.6, Z: 52, valences: [2, 4, 6], group: 'Other nonmetals', x: 16, y: 5},
  {inactive: false, symbol: 'I', name: 'Iodine', mass: 126.9, Z: 53, valences: [-1, 1, 5, 7], group: 'Other nonmetals', x: 17, y: 5},
  {inactive: true, symbol: 'Xe', name: 'Xenon', mass: 131.3, Z: 54, valences: 'doublet stable', group: 'Noble gases', x: 18, y: 5},
  {inactive: true, symbol: 'Cs', name: 'Cesium', mass: 132.9, Z: 55, valences: [1], group: 'Alkali metals', x: 1, y: 6},
  {inactive: true, symbol: 'Ba', name: 'Barium', mass: 137.3, Z: 56, valences: [2], group: 'Alkaline earth metals', x: 2, y: 6},
  {inactive: true, symbol: 'La', name: 'Lanthanum', mass: 138.9, Z: 57, valences: [3], group: 'Lanthanides', x: 4, y: 9},
  {inactive: true, symbol: 'Ce', name: 'Cerium', mass: 140.1, Z: 58, valences: [3, 4], group: 'Lanthanides', x: 5, y: 9},
  {inactive: true, symbol: 'Pr', name: 'Praseodymium', mass: 140.9, Z: 59, valences: [3, 4], group: 'Lanthanides', x: 6, y: 9},
  {inactive: true, symbol: 'Nd', name: 'Neodymium', mass: 144.2, Z: 60, valences: [3], group: 'Lanthanides', x: 7, y: 9},
  {inactive: true, symbol: 'Pm', name: 'Promethium', mass: 145.0, Z: 61, valences: [3], group: 'Lanthanides', x: 8, y: 9},
  {inactive: true, symbol: 'Sm', name: 'Samarium', mass: 150.4, Z: 62, valences: [2, 3], group: 'Lanthanides', x: 9, y: 9},
  {inactive: true, symbol: 'Eu', name: 'Europium', mass: 152.0, Z: 63, valences: [2, 3], group: 'Lanthanides', x: 10, y: 9},
  {inactive: true, symbol: 'Gd', name: 'Gadolinium', mass: 157.3, Z: 64, valences: [3], group: 'Lanthanides', x: 11, y: 9},
  {inactive: true, symbol: 'Tb', name: 'Terbium', mass: 158.9, Z: 65, valences: [3, 4], group: 'Lanthanides', x: 12, y: 9},
  {inactive: true, symbol: 'Dy', name: 'Dysprosium', mass: 162.5, Z: 66, valences: [3], group: 'Lanthanides', x: 13, y: 9},
  {inactive: true, symbol: 'Ho', name: 'Holmium', mass: 164.9, Z: 67, valences: [3], group: 'Lanthanides', x: 14, y: 9},
  {inactive: true, symbol: 'Er', name: 'Erbium', mass: 167.3, Z: 68, valences: [3], group: 'Lanthanides', x: 15, y: 9},
  {inactive: true, symbol: 'Tm', name: 'Thulium', mass: 168.9, Z: 69, valences: [2, 3], group: 'Lanthanides', x: 16, y: 9},
  {inactive: true, symbol: 'Yb', name: 'Ytterbium', mass: 173.0, Z: 70, valences: [2, 3], group: 'Lanthanides', x: 17, y: 9},
  {inactive: true, symbol: 'Lu', name: 'Lutetium', mass: 175.0, Z: 71, valences: [3], group: 'Lanthanides', x: 18, y: 9},
  {inactive: true, symbol: 'Hf', name: 'Hafnium', mass: 178.5, Z: 72, valences: [4], group: 'Transition metals', x: 4, y: 6},
  {inactive: true, symbol: 'Ta', name: 'Tantalum', mass: 180.9, Z: 73, valences: [5], group: 'Transition metals', x: 5, y: 6},
  {inactive: true, symbol: 'W', name: 'Tungsten', mass: 183.8, Z: 74, valences: [2, 4, 6], group: 'Transition metals', x: 6, y: 6},
  {inactive: true, symbol: 'Re', name: 'Rhenium', mass: 186.2, Z: 75, valences: [2, 4, 6, 7], group: 'Transition metals', x: 7, y: 6},
  {inactive: true, symbol: 'Os', name: 'Osmium', mass: 190.2, Z: 76, valences: [2, 3, 4, 6, 8], group: 'Transition metals', x: 8, y: 6},
  {inactive: true, symbol: 'Ir', name: 'Iridium', mass: 192.2, Z: 77, valences: [1, 2, 3, 4, 6], group: 'Transition metals', x: 9, y: 6},
  {inactive: true, symbol: 'Pt', name: 'Platinum', mass: 195.1, Z: 78, valences: [2, 4], group: 'Transition metals', x: 10, y: 6},
  {inactive: true, symbol: 'Au', name: 'Gold', mass: 197.0, Z: 79, valences: [1, 3], group: 'Transition metals', x: 11, y: 6},
  {inactive: true, symbol: 'Hg', name: 'Mercury', mass: 200.6, Z: 80, valences: [1, 2], group: 'Transition metals', x: 12, y: 6},
  {inactive: true, symbol: 'Tl', name: 'Thallium', mass: 204.4, Z: 81, valences: [1, 3], group: 'Other metals', x: 13, y: 6},
  {inactive: true, symbol: 'Pb', name: 'Lead', mass: 207.2, Z: 82, valences: [2, 4], group: 'Other metals', x: 14, y: 6},
  {inactive: true, symbol: 'Bi', name: 'Bismuth', mass: 208.9, Z: 83, valences: [3, 5], group: 'Other metals', x: 15, y: 6},
  {inactive: true, symbol: 'Po', name: 'Polonium', mass: 209.0, Z: 84, valences: [2, 4, 6], group: 'Other nonmetals', x: 16, y: 6},
  {inactive: true, symbol: 'At', name: 'Astatine', mass: 210.0, Z: 85, valences: [-1, 1, 3, 5, 7], group: 'Other nonmetals', x: 17, y: 6},
  {inactive: true, symbol: 'Rn', name: 'Radon', mass: 222.0, Z: 86, valences: 'doublet stable', group: 'Noble gases', x: 18, y: 6},
  {inactive: true, symbol: 'Fr', name: 'Francium', mass: 223.0, Z: 87, valences: [1], group: 'Alkali metals', x: 1, y: 7},
  {inactive: true, symbol: 'Ra', name: 'Radium', mass: 226.0, Z: 88, valences: [2], group: 'Alkaline earth metals', x: 2, y: 7},
  {inactive: true, symbol: 'Ac', name: 'Actinium', mass: 227.0, Z: 89, valences: [3], group: 'Actinides', x: 4, y: 10},
  {inactive: true, symbol: 'Th', name: 'Thorium', mass: 232.0, Z: 90, valences: [4], group: 'Actinides', x: 5, y: 10},
  {inactive: true, symbol: 'Pa', name: 'Protactinium', mass: 231.0, Z: 91, valences: [5], group: 'Actinides', x: 6, y: 10},
  {inactive: true, symbol: 'U', name: 'Uranium', mass: 238.0, Z: 92, valences: [6], group: 'Actinides', x: 7, y: 10},
  {inactive: true, symbol: 'Np', name: 'Neptunium', mass: 237.0, Z: 93, valences: [5, 6], group: 'Actinides', x: 8, y: 10},
  {inactive: true, symbol: 'Pu', name: 'Plutonium', mass: 244.0, Z: 94, valences: [3, 4, 6], group: 'Actinides', x: 9, y: 10},
  {inactive: true, symbol: 'Am', name: 'Americium', mass: 243.0, Z: 95, valences: [2, 3, 4, 5, 6], group: 'Actinides', x: 10, y: 10},
  {inactive: true, symbol: 'Cm', name: 'Curium', mass: 247.0, Z: 96, valences: [3, 4], group: 'Actinides', x: 11, y: 10},
  {inactive: true, symbol: 'Bk', name: 'Berkelium', mass: 247.0, Z: 97, valences: [3, 4], group: 'Actinides', x: 12, y: 10},
  {inactive: true, symbol: 'Cf', name: 'Californium', mass: 251.0, Z: 98, valences: [2, 3, 4], group: 'Actinides', x: 13, y: 10},
  {inactive: true, symbol: 'Es', name: 'Einsteinium', mass: 252.0, Z: 99, valences: [2, 3], group: 'Actinides', x: 14, y: 10},
  {inactive: true, symbol: 'Fm', name: 'Fermium', mass: 257.0, Z: 100, valences: [2, 3], group: 'Actinides', x: 15, y: 10},
  {inactive: true, symbol: 'Md', name: 'Mendelevium', mass: 258.0, Z: 101, valences: [2, 3], group: 'Actinides', x: 16, y: 10},
  {inactive: true, symbol: 'No', name: 'Nobelium', mass: 259.0, Z: 102, valences: [2, 3], group: 'Actinides', x: 17, y: 10},
  {inactive: true, symbol: 'Lr', name: 'Lawrencium', mass: 266.0, Z: 103, valences: [3], group: 'Transition metals', x: 18, y: 10},
  {inactive: true, symbol: 'Rf', name: 'Rutherfordium', mass: 267.0, Z: 104, valences: [4], group: 'Transition metals', x: 4, y: 7},
  {inactive: true, symbol: 'Db', name: 'Dubnium', mass: 270.0, Z: 105, valences: [5], group: 'Transition metals', x: 5, y: 7},
  {inactive: true, symbol: 'Sg', name: 'Seaborgium', mass: 271.0, Z: 106, valences: [6], group: 'Transition metals', x: 6, y: 7},
  {inactive: true, symbol: 'Bh', name: 'Bohrium', mass: 270.0, Z: 107, valences: [7], group: 'Transition metals', x: 7, y: 7},
  {inactive: true, symbol: 'Hs', name: 'Hassium', mass: 277.0, Z: 108, valences: [8], group: 'Transition metals', x: 8, y: 7},
  {inactive: true, symbol: 'Mt', name: 'Meitnerium', mass: 278.0, Z: 109, valences: [9], group: 'Transition metals', x: 9, y: 7},
  {inactive: true, symbol: 'Ds', name: 'Darmstadtium', mass: 281.0, Z: 110, valences: [10], group: 'Transition metals', x: 10, y: 7},
  {inactive: true, symbol: 'Rg', name: 'Roentgenium', mass: 282.0, Z: 111, valences: [11], group: 'Transition metals', x: 11, y: 7},
  {inactive: true, symbol: 'Cn', name: 'Copernicium', mass: 285.0, Z: 112, valences: [12], group: 'Transition metals', x: 12, y: 7},
  {inactive: true, symbol: 'Nh', name: 'Nihonium', mass: 284.0, Z: 113, valences: [1, 3], group: 'Other metals', x: 13, y: 7},
  {inactive: true, symbol: 'Fl', name: 'Flerovium', mass: 289.0, Z: 114, valences: [1, 2, 4, 6], group: 'Other metals', x: 14, y: 7},
  {inactive: true, symbol: 'Mc', name: 'Moscovium', mass: 288.0, Z: 115, valences: [1, 3], group: 'Other metals', x: 15, y: 7},
  {inactive: true, symbol: 'Lv', name: 'Livermorium', mass: 293.0, Z: 116, valences: [1, 2], group: 'Other metals', x: 16, y: 7},
  {inactive: true, symbol: 'Ts', name: 'Tennessine', mass: 294.0, Z: 117, valences: [1], group: 'Other nonmetals', x: 17, y: 7},
  {inactive: true, symbol: 'Og', name: 'Oganesson', mass: 294.0, Z: 118, valences: 'unknown', group: 'Noble gases', x: 18, y: 7},
];